import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Navbar'
import Footer from '@/Components/Footer';
import Test from '@/Components/Test';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OpenSoftTech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      
      {children}
      <Footer />
      <Test />
      </body>
    </html>
  )
}
